### ISSUE TITLE
Not Working/Hanging on Modulus

### ISSUE THREAD

**Issue by themeteorchef** [lufrai/spiderable2#1]
Thanks for this package! Been stuck on this for awhile. Here's what I'm finding...

1.) Works like a charm on localhost.
2.) Appears to work on a deploy to Modulus, but either returns immediately not rendering any content to the page (view source looks like standard Meteor), or, hangs for ~30-60 seconds plus (with no results).

Any thoughts?

For reference, I'm just hitting a URL like `http://site.com/page?_escaped_fragment_=`.

**Comment by katywings** [comment]
hey there!

You are welcome :)

Sad to hear that its not working for you!

Okay lets try some things:
- can you please activate verbose logging:
  Via Meteor Setting config json file
  {
  spiderable2: {
      verbose: true
  }
  }

And send me the output of the server console (when you hit the page in the browser this will log several things at the server console)

**Comment by chaffinated** [comment]
Hi. I'm having this issue, too. I enabled verbose mode, and the only output is:

Loading page content from: http://localhost:3000/

Looks like things are getting hung up on the call to `zombie.visit` in `Spiderable2.loadBody`. After about 30 seconds of trying, it sends over the "Unable to connect to any application instances" message.

I'm wondering if localhost:3000 isn't a problem for some reason.

**Comment by chaffinated** [comment]
Derp. Seems like the port to listen to was 8080. Forgot to check before deploying.

**Comment by chaffinated** [comment]
Also, thanks a bunch for your work on this! I was having a difficult time getting around the phantomjs "bind" hitch.

**Comment by katywings** [comment]
Hey silent creeper :P

Thank you for your feedback, I really appreciate it!

You're welcome :D, unless you explode in front of my house!

Im glad you could solve the connection problems. If you have any questions in future, just ask ;).

**Comment by katywings** [comment]
I think I will add a connection test at server start :)

**Comment by themeteorchef** [comment]
@katywings Finally got around to testing this and it looks like the port thing did the trick! I was deploying using port `3000` originally, but making sure my production settings used `8080` is working great. Going to close this as resolved :) Thanks again for getting this package together.
