### ISSUE TITLE
Not working (localhost)

### ISSUE THREAD

**Issue by olivierpascal** [lufrai/spiderable2#5]
On localhost: added by `meteor add lufrai:spiderable2', edited settings.json by adding:

```
"spiderable2": {
  "timeout": 1000,
  "port"   : 3000,
  "verbose": true
}
```

Trying with `curl -v "http://localhost:3000/?_escaped_fragment_="`

And nothing happening, it just hangs out. No output, no logs.

**Comment by katywings** [comment]
Thx for the information, just for completeness:
The curl command, did you ran that within the docker container?
How are the ports binded? 3000:3000? 
And does it work in your dev environment?

**Comment by olivierpascal** [comment]
The test was done locally, in dev env (just launched meteor --settings settings.json).

**Comment by katywings** [comment]
Im sorry ive never answered to your message. Have you already found a solution?

What is the os youre using?
Can you send me a list of the packages you are using?
Without an actual error message its really difficult to help from external :(
