### ISSUE TITLE
Compatible with fastrender?

### ISSUE THREAD

**Issue by lowi** [lufrai/spiderable2#6]
I am trying to get your package to work with my application, and currently I have the following behavior:
1. Fastrender creates a page with a `<script>` tag that injects the data
2. The script tag is scrapped in in spiderable_server.js by
   `result = result.replace( /<script[^>]+>(.|\n|\r)*?<\/script\s*>/ig, '' );`

If I disable fastrender, it sometimes display something and sometimes not.
What is the recommended way to use the package with fastrender?

**Comment by katywings** [comment]
Hey lowi

I will look at it. But i need to warn you, it is pretty much impossible to make spiderable compatible to the whole lot packages which manipulate the output of Meteor...

Edit: Sorry that I newer answered.. I was away from the meteor community quite some time, have you found a solution for this issue already?
