### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by dnish** [lufrai/spiderable2#7]
Hey,
I try to use it with the current meteor version on my dev machine (Win 10), but I can't add it:

error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

**Comment by dariuszsikorski** [comment]
I have the same issue. Meteor 1.1.0.3 with iron-router installed.

**Comment by katywings** [comment]
Hello hello, sorry for my late answer! Do you guys still use Meteor? Did they fix the problems with the spiderable core package? I am quite outdated on this one ^^

**Comment by dnish** [comment]
Yeah, since Meteor 1.3 we can use the original package via npm.

**Comment by katywings** [comment]
Thank you a lot for your fast feedback!
