### ISSUE TITLE
Zombie seemingly can't connect to server under Docker - how to fix?

### ISSUE THREAD

**Issue by aknuds1** [lufrai/spiderable2#8]
I'm having the problem that Spiderable2 won't work once deployed to Docker, from the looks of it it's because Zombie can't connect to the server on `http://localhost:80`.

Now, the Meteor Docker container doesn't expose port 80 to the outside world, although it uses port 80 in its container, instead it has an Nginx reverse proxy in front of it. I'm wondering if this is the problem, that Zombie cannot access localhost:80, even though it runs within the same container as the Meteor app? Do you know how to resolve this issue?

**Comment by aknuds1** [comment]
After some further research, it seems Zombie simply doesn't load my site properly for some reason. I guess the suspected Docker issue might be a red herring.

**Comment by katywings** [comment]
Hey hey, sorry for my late answer ^^, are you still searching for a solution for this one?

**Comment by aknuds1** [comment]
Haven't used Zombie for some time, so going to close this one.
